# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config  -id {[Synth 8-3352]}  -new_severity {CRITICAL WARNING} 
set_msg_config  -id {[Opt 31-35]}  -new_severity {INFO} 
set_msg_config  -id {[Opt 31-32]}  -new_severity {INFO} 
set_msg_config  -id {[Shape Builder 18-119]}  -new_severity {WARNING} 
set_msg_config  -id {[Filemgmt 20-742]}  -new_severity {ERROR} 
set_msg_config  -id {[Synth 8-350]}  -new_severity {CRITICAL WARNING} 
set_msg_config  -id {[Synth 8-2490]}  -new_severity {WARNING} 
set_msg_config  -id {[Synth 8-2306]}  -new_severity {INFO} 
set_msg_config  -id {[Synth 8-3331]}  -new_severity {CRITICAL WARNING} 
set_msg_config  -id {[Synth 8-3332]}  -new_severity {INFO} 
set_msg_config  -id {[Synth 8-2715]}  -new_severity {ERROR} 
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/gab/Desktop/FPU_PULP/pulpino/fpga/pulpino/pulpino.cache/wt [current_project]
set_property parent.project_path /home/gab/Desktop/FPU_PULP/pulpino/fpga/pulpino/pulpino.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:0.9 [current_project]
set_property include_dirs {
  /home/gab/Desktop/FPU_PULP/pulpino/rtl/includes
  /home/gab/Desktop/FPU_PULP/pulpino/ips/axi/axi_node
  /home/gab/Desktop/FPU_PULP/pulpino/ips/apb/apb_event_unit/include
  /home/gab/Desktop/FPU_PULP/pulpino/ips/fpu
  /home/gab/Desktop/FPU_PULP/pulpino/ips/apb/apb_i2c
  /home/gab/Desktop/FPU_PULP/pulpino/ips/zero-riscy/include
  /home/gab/Desktop/FPU_PULP/pulpino/ips/zero-riscy/include
  /home/gab/Desktop/FPU_PULP/pulpino/ips/riscv/include
  /home/gab/Desktop/FPU_PULP/pulpino/rtl/includes
  /home/gab/Desktop/FPU_PULP/pulpino/ips/riscv/include
  /home/gab/Desktop/FPU_PULP/pulpino/ips/adv_dbg_if/rtl
} [current_fileset]
set_property verilog_define {PULP_FPGA_EMUL=1 RISCV} [current_fileset]
set_property generic {USE_ZERO_RISCY=0 RISCY_RV32F=0 ZERO_RV32M=0 ZERO_RV32E=0} [current_fileset]
add_files -quiet /home/gab/Desktop/FPU_PULP/pulpino/fpga/ips/xilinx_mem_8192x32/ip/xilinx_mem_8192x32.dcp
set_property used_in_implementation false [get_files /home/gab/Desktop/FPU_PULP/pulpino/fpga/ips/xilinx_mem_8192x32/ip/xilinx_mem_8192x32.dcp]
add_files -quiet /home/gab/Desktop/FPU_PULP/pulpino/fpga/ips/xilinx_fp_fma/ip/xilinx_fp_fma.dcp
set_property used_in_implementation false [get_files /home/gab/Desktop/FPU_PULP/pulpino/fpga/ips/xilinx_fp_fma/ip/xilinx_fp_fma.dcp]
read_verilog {
  /home/gab/Desktop/FPU_PULP/pulpino/ips/axi/axi_node/defines.v
  /home/gab/Desktop/FPU_PULP/pulpino/ips/apb/apb_event_unit/include/defines_event_unit.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/apb/apb_i2c/i2c_master_defines.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/riscv/include/apu_macros.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/riscv/include/riscv_config.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/adv_dbg_if/rtl/adbg_axi_defines.v
  /home/gab/Desktop/FPU_PULP/pulpino/ips/adv_dbg_if/rtl/adbg_defines.v
  /home/gab/Desktop/FPU_PULP/pulpino/ips/adv_dbg_if/rtl/adbg_or1k_defines.v
  /home/gab/Desktop/FPU_PULP/pulpino/ips/adv_dbg_if/rtl/adbg_tap_defines.v
}
set_property file_type "Verilog Header" [get_files /home/gab/Desktop/FPU_PULP/pulpino/ips/axi/axi_node/defines.v]
set_property file_type "Verilog Header" [get_files /home/gab/Desktop/FPU_PULP/pulpino/ips/apb/apb_event_unit/include/defines_event_unit.sv]
set_property file_type "Verilog Header" [get_files /home/gab/Desktop/FPU_PULP/pulpino/ips/apb/apb_i2c/i2c_master_defines.sv]
set_property file_type "Verilog Header" [get_files /home/gab/Desktop/FPU_PULP/pulpino/ips/riscv/include/apu_macros.sv]
set_property file_type "Verilog Header" [get_files /home/gab/Desktop/FPU_PULP/pulpino/ips/riscv/include/riscv_config.sv]
set_property file_type "Verilog Header" [get_files /home/gab/Desktop/FPU_PULP/pulpino/ips/adv_dbg_if/rtl/adbg_axi_defines.v]
set_property file_type "Verilog Header" [get_files /home/gab/Desktop/FPU_PULP/pulpino/ips/adv_dbg_if/rtl/adbg_defines.v]
set_property file_type "Verilog Header" [get_files /home/gab/Desktop/FPU_PULP/pulpino/ips/adv_dbg_if/rtl/adbg_or1k_defines.v]
set_property file_type "Verilog Header" [get_files /home/gab/Desktop/FPU_PULP/pulpino/ips/adv_dbg_if/rtl/adbg_tap_defines.v]
read_verilog -library xil_defaultlib -sv {
  /home/gab/Desktop/FPU_PULP/pulpino/ips/axi/axi_node/axi_address_decoder_AR.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/axi/axi_node/axi_address_decoder_AW.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/axi/axi_node/axi_address_decoder_BR.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/axi/axi_node/axi_address_decoder_BW.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/axi/axi_node/axi_address_decoder_DW.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/axi/axi_node/axi_AR_allocator.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/axi/axi_node/axi_ArbitrationTree.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/axi/axi_node/axi_AW_allocator.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/axi/axi_node/axi_BR_allocator.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/axi/axi_node/axi_BW_allocator.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/axi/axi_node/axi_DW_allocator.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/axi/axi_node/axi_FanInPrimitive_Req.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/axi/axi_node/axi_multiplexer.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/axi/axi_node/axi_node.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/axi/axi_node/axi_request_block.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/axi/axi_node/axi_response_block.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/axi/axi_node/axi_RR_Flag_Req.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/apb/apb_node/apb_node.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/apb/apb_node/apb_node_wrap.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/axi/axi_mem_if_DP/axi_mem_if_SP.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/axi/axi_mem_if_DP/axi_read_only_ctrl.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/axi/axi_mem_if_DP/axi_write_only_ctrl.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/axi/axi_spi_slave/axi_spi_slave.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/axi/axi_spi_slave/spi_slave_axi_plug.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/axi/axi_spi_slave/spi_slave_cmd_parser.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/axi/axi_spi_slave/spi_slave_controller.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/axi/axi_spi_slave/spi_slave_dc_fifo.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/axi/axi_spi_slave/spi_slave_regs.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/axi/axi_spi_slave/spi_slave_rx.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/axi/axi_spi_slave/spi_slave_syncro.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/axi/axi_spi_slave/spi_slave_tx.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/apb/apb_gpio/apb_gpio.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/apb/apb_event_unit/apb_event_unit.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/apb/apb_event_unit/generic_service_unit.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/apb/apb_event_unit/sleep_unit.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/apb/apb_spi_master/apb_spi_master.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/apb/apb_spi_master/spi_master_apb_if.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/apb/apb_spi_master/spi_master_clkgen.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/apb/apb_spi_master/spi_master_controller.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/apb/apb_spi_master/spi_master_fifo.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/apb/apb_spi_master/spi_master_rx.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/apb/apb_spi_master/spi_master_tx.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/fpu/hdl/fpu_utils/fpu_ff.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/fpu/hdl/fpu_v0.1/fpu_defs.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/fpu/hdl/fpu_v0.1/fpexc.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/fpu/hdl/fpu_v0.1/fpu_add.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/fpu/hdl/fpu_v0.1/fpu_core.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/fpu/hdl/fpu_v0.1/fpu_ftoi.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/fpu/hdl/fpu_v0.1/fpu_itof.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/fpu/hdl/fpu_v0.1/fpu_mult.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/fpu/hdl/fpu_v0.1/fpu_norm.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/fpu/hdl/fpu_v0.1/fpu_private.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/fpu/hdl/fpu_div_sqrt_tp_nlp/fpu_defs_div_sqrt_tp.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/fpu/hdl/fpu_div_sqrt_tp_nlp/control_tp.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/fpu/hdl/fpu_div_sqrt_tp_nlp/fpu_norm_div_sqrt.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/fpu/hdl/fpu_div_sqrt_tp_nlp/iteration_div_sqrt_first.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/fpu/hdl/fpu_div_sqrt_tp_nlp/iteration_div_sqrt.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/fpu/hdl/fpu_div_sqrt_tp_nlp/nrbd_nrsc_tp.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/fpu/hdl/fpu_div_sqrt_tp_nlp/preprocess.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/fpu/hdl/fpu_div_sqrt_tp_nlp/div_sqrt_top_tp.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/apb/apb_pulpino/apb_pulpino.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/apb/apb_fll_if/apb_fll_if.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/axi/core2axi/core2axi.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/apb/apb_timer/apb_timer.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/apb/apb_timer/timer.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/axi/axi2apb/axi2apb.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/axi/axi2apb/axi2apb32.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/apb/apb_i2c/apb_i2c.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/apb/apb_i2c/i2c_master_bit_ctrl.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/apb/apb_i2c/i2c_master_byte_ctrl.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/riscv/include/apu_core_package.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/riscv/include/riscv_defines.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/riscv/riscv_alu.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/riscv/riscv_alu_div.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/riscv/riscv_compressed_decoder.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/riscv/riscv_controller.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/riscv/riscv_cs_registers.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/riscv/riscv_debug_unit.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/riscv/riscv_decoder.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/riscv/riscv_int_controller.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/riscv/riscv_ex_stage.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/riscv/riscv_hwloop_controller.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/riscv/riscv_hwloop_regs.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/riscv/riscv_id_stage.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/riscv/riscv_if_stage.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/riscv/riscv_load_store_unit.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/riscv/riscv_mult.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/riscv/riscv_prefetch_buffer.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/riscv/riscv_prefetch_L0_buffer.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/riscv/riscv_core.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/riscv/riscv_apu_disp.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/riscv/riscv_fetch_fifo.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/riscv/riscv_L0_buffer.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/riscv/riscv_register_file.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/axi/axi_slice/axi_ar_buffer.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/axi/axi_slice/axi_aw_buffer.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/axi/axi_slice/axi_b_buffer.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/axi/axi_slice/axi_r_buffer.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/axi/axi_slice/axi_slice.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/axi/axi_slice/axi_w_buffer.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/adv_dbg_if/rtl/adbg_axi_biu.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/adv_dbg_if/rtl/adbg_axi_module.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/adv_dbg_if/rtl/adbg_or1k_biu.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/adv_dbg_if/rtl/adbg_or1k_module.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/adv_dbg_if/rtl/adbg_or1k_status_reg.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/adv_dbg_if/rtl/adbg_top.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/adv_dbg_if/rtl/adv_dbg_if.sv
  /home/gab/Desktop/FPU_PULP/pulpino/ips/apb/apb2per/apb2per.sv
  /home/gab/Desktop/FPU_PULP/pulpino/rtl/components/cluster_clock_gating.sv
  /home/gab/Desktop/FPU_PULP/pulpino/rtl/components/cluster_clock_inverter.sv
  /home/gab/Desktop/FPU_PULP/pulpino/rtl/components/cluster_clock_mux2.sv
  /home/gab/Desktop/FPU_PULP/pulpino/rtl/components/rstgen.sv
  /home/gab/Desktop/FPU_PULP/pulpino/rtl/components/pulp_clock_inverter.sv
  /home/gab/Desktop/FPU_PULP/pulpino/rtl/components/pulp_clock_mux2.sv
  /home/gab/Desktop/FPU_PULP/pulpino/rtl/components/generic_fifo.sv
  /home/gab/Desktop/FPU_PULP/pulpino/rtl/axi2apb_wrap.sv
  /home/gab/Desktop/FPU_PULP/pulpino/rtl/periph_bus_wrap.sv
  /home/gab/Desktop/FPU_PULP/pulpino/rtl/core2axi_wrap.sv
  /home/gab/Desktop/FPU_PULP/pulpino/rtl/axi_node_intf_wrap.sv
  /home/gab/Desktop/FPU_PULP/pulpino/rtl/axi_spi_slave_wrap.sv
  /home/gab/Desktop/FPU_PULP/pulpino/rtl/axi_slice_wrap.sv
  /home/gab/Desktop/FPU_PULP/pulpino/rtl/axi_mem_if_SP_wrap.sv
  /home/gab/Desktop/FPU_PULP/pulpino/rtl/core_region.sv
  /home/gab/Desktop/FPU_PULP/pulpino/rtl/instr_ram_wrap.sv
  /home/gab/Desktop/FPU_PULP/pulpino/rtl/sp_ram_wrap.sv
  /home/gab/Desktop/FPU_PULP/pulpino/rtl/boot_code.sv
  /home/gab/Desktop/FPU_PULP/pulpino/rtl/boot_rom_wrap.sv
  /home/gab/Desktop/FPU_PULP/pulpino/rtl/peripherals.sv
  /home/gab/Desktop/FPU_PULP/pulpino/rtl/ram_mux.sv
  /home/gab/Desktop/FPU_PULP/pulpino/rtl/pulpino_top.sv
  /home/gab/Desktop/FPU_PULP/pulpino/rtl/clk_rst_gen.sv
}
read_verilog -library xil_defaultlib {
  /home/gab/Desktop/FPU_PULP/pulpino/ips/axi/axi_slice_dc/dc_data_buffer.v
  /home/gab/Desktop/FPU_PULP/pulpino/ips/axi/axi_slice_dc/dc_full_detector.v
  /home/gab/Desktop/FPU_PULP/pulpino/ips/axi/axi_slice_dc/dc_synchronizer.v
  /home/gab/Desktop/FPU_PULP/pulpino/ips/axi/axi_slice_dc/dc_token_ring_fifo_din.v
  /home/gab/Desktop/FPU_PULP/pulpino/ips/axi/axi_slice_dc/dc_token_ring_fifo_dout.v
  /home/gab/Desktop/FPU_PULP/pulpino/ips/axi/axi_slice_dc/dc_token_ring.v
  /home/gab/Desktop/FPU_PULP/pulpino/ips/adv_dbg_if/rtl/adbg_crc32.v
  /home/gab/Desktop/FPU_PULP/pulpino/ips/adv_dbg_if/rtl/adbg_tap_top.v
  /home/gab/Desktop/FPU_PULP/pulpino/fpga/rtl/pulpino_wrap.v
}
read_vhdl -library xil_defaultlib {
  /home/gab/Desktop/FPU_PULP/pulpino/ips/apb/apb_uart/apb_uart.vhd
  /home/gab/Desktop/FPU_PULP/pulpino/ips/apb/apb_uart/slib_clock_div.vhd
  /home/gab/Desktop/FPU_PULP/pulpino/ips/apb/apb_uart/slib_counter.vhd
  /home/gab/Desktop/FPU_PULP/pulpino/ips/apb/apb_uart/slib_edge_detect.vhd
  /home/gab/Desktop/FPU_PULP/pulpino/ips/apb/apb_uart/slib_fifo.vhd
  /home/gab/Desktop/FPU_PULP/pulpino/ips/apb/apb_uart/slib_input_filter.vhd
  /home/gab/Desktop/FPU_PULP/pulpino/ips/apb/apb_uart/slib_input_sync.vhd
  /home/gab/Desktop/FPU_PULP/pulpino/ips/apb/apb_uart/slib_mv_filter.vhd
  /home/gab/Desktop/FPU_PULP/pulpino/ips/apb/apb_uart/uart_baudgen.vhd
  /home/gab/Desktop/FPU_PULP/pulpino/ips/apb/apb_uart/uart_interrupt.vhd
  /home/gab/Desktop/FPU_PULP/pulpino/ips/apb/apb_uart/uart_receiver.vhd
  /home/gab/Desktop/FPU_PULP/pulpino/ips/apb/apb_uart/uart_transmitter.vhd
  /home/gab/Desktop/FPU_PULP/pulpino/fpga/pulpino/pulpino.srcs/sources_1/new/TMR.vhd
}
read_xdc /home/gab/Desktop/FPU_PULP/pulpino/fpga/pulpino/constraints.xdc
set_property used_in_implementation false [get_files /home/gab/Desktop/FPU_PULP/pulpino/fpga/pulpino/constraints.xdc]

synth_design -top pulpino -part xc7z020clg484-1 -directive AreaOptimizedHigh -control_set_opt_threshold 1
write_checkpoint -noxdef pulpino.dcp
catch { report_utilization -file pulpino_utilization_synth.rpt -pb pulpino_utilization_synth.pb }
